"""Generate report.md for decision-simplification-frameworks batch.

Mechanical compile per /research-report skill spec: every field, every item,
TOC linking to per-item sections. Skips fields listed in `uncertain` and
fields whose value contains '[uncertain]'.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

import yaml

TOPIC_DIR = Path(__file__).parent
RESULTS_DIR = TOPIC_DIR / "results"
OUTLINE_PATH = TOPIC_DIR / "outline.yaml"
FIELDS_PATH = TOPIC_DIR / "fields.yaml"
REPORT_PATH = TOPIC_DIR / "report.md"

NAME_FIELD = "framework_name"  # top-level key holding the canonical item name
TOC_FIELDS = ["adoption_verdict", "signal_type", "implementation_complexity"]

CATEGORY_DISPLAY = {
    "basic_info": "Basic Info",
    "mechanic": "Mechanic",
    "evidence_base": "Evidence Base",
    "group_decision_fit": "Group Decision Fit",
    "quiz_mapping": "Quiz Mapping",
    "recommendation": "Recommendation",
    "sources": "Sources",
}


def slugify(text: str) -> str:
    text = text.lower()
    text = re.sub(r"[^\w\s-]", "", text)
    text = re.sub(r"[\s_]+", "-", text).strip("-")
    return text


def is_uncertain(value, field_name: str, uncertain_list: list[str]) -> bool:
    if field_name in uncertain_list:
        return True
    if value is None:
        return True
    if isinstance(value, str):
        if not value.strip():
            return True
        if "[uncertain]" in value.lower():
            return True
    if isinstance(value, list) and len(value) == 0:
        return True
    return False


def format_value(value) -> str:
    if isinstance(value, str):
        return value.strip()
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, list):
        if all(isinstance(v, dict) for v in value):
            lines = []
            for item in value:
                pairs = [f"{k}: {v}" for k, v in item.items()]
                lines.append(" | ".join(pairs))
            return "\n".join(f"- {line}" for line in lines)
        if all(isinstance(v, str) for v in value):
            if sum(len(v) for v in value) < 200 and len(value) <= 5:
                return ", ".join(v.strip() for v in value)
            return "\n".join(f"- {v.strip()}" for v in value)
        return "\n".join(f"- {v}" for v in value)
    if isinstance(value, dict):
        return "\n".join(f"- **{k}**: {v}" for k, v in value.items())
    return str(value)


def short(value, limit: int = 80) -> str:
    s = format_value(value).splitlines()[0]
    s = s.replace("|", "\\|")
    if len(s) > limit:
        s = s[: limit - 1].rstrip() + "…"
    return s


def main() -> None:
    fields_def = yaml.safe_load(FIELDS_PATH.read_text(encoding="utf-8"))
    field_categories = fields_def["field_categories"]

    items: list[dict] = []
    for json_path in sorted(RESULTS_DIR.glob("*.json")):
        data = json.loads(json_path.read_text(encoding="utf-8"))
        data["_source_file"] = json_path.name
        items.append(data)

    out: list[str] = []
    out.append(f"# Decision-Simplification Frameworks — Compiled Report")
    out.append("")
    out.append(
        "Mechanical compile of every field for every framework. Generated by "
        "`generate_report.py` from `outline.yaml`, `fields.yaml`, and `results/*.json`. "
        "Source for layer-2 synthesis in `50_product/`."
    )
    out.append("")
    out.append(f"**Items:** {len(items)}  ")
    out.append(f"**Source JSONs:** `01_raw/decision-simplification-frameworks/results/`  ")
    out.append("**TOC summary fields:** " + ", ".join(f"`{f}`" for f in TOC_FIELDS))
    out.append("")
    out.append("## Table of Contents")
    out.append("")
    for i, item in enumerate(items, 1):
        name = item.get(NAME_FIELD, item["_source_file"].replace(".json", ""))
        anchor = slugify(name)
        bits = [f"{i}. [{name}](#{anchor})"]
        toc_bits = []
        for tf in TOC_FIELDS:
            val = item.get(tf)
            if val and not is_uncertain(val, tf, item.get("uncertain", [])):
                toc_bits.append(f"**{tf}**: {short(val)}")
        if toc_bits:
            bits.append(" — " + " · ".join(toc_bits))
        out.append("".join(bits))
    out.append("")

    defined_keys: set[str] = set()
    for cat in field_categories:
        for f in cat["fields"]:
            defined_keys.add(f["name"])

    for item in items:
        name = item.get(NAME_FIELD, item["_source_file"].replace(".json", ""))
        uncertain_list = item.get("uncertain", []) or []
        out.append(f"## {name}")
        out.append("")
        out.append(f"_Source: `{item['_source_file']}`_")
        out.append("")
        for cat in field_categories:
            cat_label = CATEGORY_DISPLAY.get(cat["category"], cat["category"])
            cat_block: list[str] = []
            for f in cat["fields"]:
                fname = f["name"]
                value = item.get(fname)
                if is_uncertain(value, fname, uncertain_list):
                    continue
                formatted = format_value(value)
                if "\n" in formatted:
                    cat_block.append(f"**{fname}**:")
                    cat_block.append("")
                    cat_block.append(formatted)
                    cat_block.append("")
                else:
                    cat_block.append(f"**{fname}**: {formatted}")
                    cat_block.append("")
            if cat_block:
                out.append(f"### {cat_label}")
                out.append("")
                out.extend(cat_block)
        extras = {
            k: v
            for k, v in item.items()
            if k not in defined_keys
            and k not in {"_source_file", "uncertain", NAME_FIELD}
        }
        if extras:
            out.append("### Other Info")
            out.append("")
            for k, v in extras.items():
                if is_uncertain(v, k, uncertain_list):
                    continue
                formatted = format_value(v)
                if "\n" in formatted:
                    out.append(f"**{k}**:")
                    out.append("")
                    out.append(formatted)
                    out.append("")
                else:
                    out.append(f"**{k}**: {formatted}")
                    out.append("")
        if uncertain_list:
            out.append("### Uncertain fields")
            out.append("")
            for u in uncertain_list:
                out.append(f"- `{u}`")
            out.append("")
        out.append("---")
        out.append("")

    REPORT_PATH.write_text("\n".join(out), encoding="utf-8")
    print(f"Wrote {REPORT_PATH} ({len(items)} items)")


if __name__ == "__main__":
    main()
