-- tb-WF-13 (workflow-overhaul) — claim_codes table.
--
-- The mint half of the web-invitee account-claim bridge. Per ADR 0015
-- (60_engineering/adr/0015-web-invitee-account-claim-bridge.md) a Web
-- invitee who votes in the browser and then installs the iOS app gets a
-- fresh, disjoint Apple `user_id` — their browser vote strands. The
-- bridge is a single-use claim code that carries the browser's
-- anonymous Supabase session into the freshly-installed app *before* the
-- Apple tap, so the Apple tap becomes `linkApple` (preserving the
-- anonymous `user_id`) instead of `signInWithApple`.
--
-- This table is the carrier. It maps a short, unguessable, single-use
-- code to the web anonymous session's refresh token — encrypted at rest
-- — with a ~30-minute TTL and a redeemed-at marker.
--
-- ── Why the row holds a refresh token at all ─────────────────────────
-- There is no Supabase primitive to mint a session for an arbitrary
-- anonymous user from the server. The only way the app can resume the
-- exact web anonymous identity is to install that session's refresh
-- token into its own keychain. So the code must carry the session key
-- itself (ADR 0015 §Consequences "The server briefly holds a refresh
-- token"). The stakes are low — the protected asset is one anonymous
-- web invitee's vote in one dinner Plan — but the token is still
-- encrypted at rest and the row is single-use + short-TTL to keep the
-- exposure window tight.
--
-- ── Why the refresh token is stored encrypted, not plaintext ─────────
-- The `mint-claim-code` Edge Function encrypts the refresh token with
-- AES-GCM (a runtime `CLAIM_CODE_ENC_KEY` secret) before the INSERT;
-- `redeem-claim-code` (tb-WF-14) decrypts after the lookup. The
-- ciphertext column therefore never holds a usable token even to anyone
-- who somehow reads the row directly. The encryption is application-
-- layer (in the Edge Function), not a Postgres `pgcrypto` column
-- default, so the key never lives in the database.
--
-- ── RLS posture — service-role only, no client path ──────────────────
-- This table is reachable ONLY by the two Edge Functions, which use the
-- service-role key (it bypasses RLS). No browser and no app client ever
-- touches `claim_codes` directly:
--   * mint  — the web client calls the `mint-claim-code` function with
--             its live session JWT; the function (service-role) writes
--             the row.
--   * redeem — the app calls `redeem-claim-code` with the bare code;
--             the function (service-role) reads + marks the row.
-- Following the `app_config` precedent (bug-09 migration): RLS is
-- enabled with NO policies, and all table grants are revoked from the
-- `anon` / `authenticated` PostgREST roles. With RLS on and no policy,
-- every non-superuser role is denied; the revoke is belt-and-braces so
-- the table is also unreachable over PostgREST entirely.
--
-- ── Down-migration ──────────────────────────────────────────────────
-- Drop the table. Reversible — the only data lost is in-flight claim
-- codes, which a Web invitee re-mints from the "Getting the app?"
-- affordance (re-mintable by design).

-- ── 1. claim_codes table ────────────────────────────────────────────

create table if not exists public.claim_codes (
    -- The claim code itself — the primary key. 8 characters from an
    -- unambiguous alphabet (no O/0, I/1/l), generated by the
    -- `mint-claim-code` Edge Function. Stored uppercase; the redeem
    -- side uppercases the user's typed input before the lookup.
    code             text primary key,

    -- The web anonymous session's refresh token, encrypted at rest by
    -- the `mint-claim-code` Edge Function (AES-GCM). Opaque ciphertext
    -- — never a usable token at rest.
    encrypted_token  text not null,

    -- The web invitee's anonymous `user_id`, recorded for observability
    -- and so the redeem side can sanity-check what it is about to
    -- install. NOT a foreign key to auth.users: the anonymous identity
    -- may be purged by the 30-day TTL sweeper before the code is
    -- redeemed, and a stale claim_codes row is harmless (it simply
    -- fails to redeem) — an FK cascade would be extra coupling for no
    -- benefit.
    user_id          uuid not null,

    -- Mint timestamp. Defaults to now() so the Edge Function need not
    -- supply it.
    created_at       timestamptz not null default now(),

    -- Expiry — ~30 minutes after mint. The redeem side rejects a code
    -- whose expires_at is in the past. The default keeps the TTL in one
    -- place; the Edge Function can still pass an explicit value.
    expires_at       timestamptz not null default (now() + interval '30 minutes'),

    -- Single-use marker. NULL until the code is redeemed; set to the
    -- redemption time by `redeem-claim-code`. A non-NULL value means the
    -- code is spent and must be rejected on any further redeem attempt.
    redeemed_at      timestamptz
);

comment on table public.claim_codes is
    'tb-WF-13 / ADR 0015 — the carrier table for the web-invitee '
    'account-claim bridge. Maps a single-use, ~30-min-TTL, 8-char '
    'unambiguous code to a web anonymous session''s refresh token '
    '(AES-GCM encrypted at rest by the mint-claim-code Edge Function). '
    'RLS-locked: no policies, no anon/authenticated grant; reached only '
    'by the mint-claim-code / redeem-claim-code Edge Functions via the '
    'service-role key.';

comment on column public.claim_codes.code is
    'tb-WF-13 — the claim code. 8 chars from an unambiguous alphabet '
    '(no O/0, I/1/l), uppercase. Primary key — uniqueness is enforced '
    'here; the mint function retries on the rare collision.';

comment on column public.claim_codes.encrypted_token is
    'tb-WF-13 — the web anonymous session refresh token, AES-GCM '
    'encrypted by the mint-claim-code Edge Function. Opaque at rest.';

comment on column public.claim_codes.redeemed_at is
    'tb-WF-13 — single-use marker. NULL = unredeemed; non-NULL = spent. '
    'redeem-claim-code rejects any code with a non-NULL redeemed_at.';

-- ── 2. Lock RLS — service-role only ─────────────────────────────────
-- RLS on, no policies created: every non-superuser role is denied.
-- The revoke strips the default PostgREST table grants so anon /
-- authenticated cannot reach the table at all. The service-role key
-- (used by the two Edge Functions) bypasses RLS, which is the only
-- access path by design.

alter table public.claim_codes enable row level security;

revoke all on table public.claim_codes from anon, authenticated;

-- ── 3. Lookup index on expires_at ───────────────────────────────────
-- A stale-row sweep (or a future TTL cron) scans by expiry; the index
-- keeps that cheap. The primary key already covers the code lookup the
-- redeem path uses.

create index if not exists claim_codes_expires_at_idx
    on public.claim_codes (expires_at);
