-- TB-06 — verdicts + option_cuts schema.
--
-- The two tables that own the VerdictEngine's output. The engine itself
-- runs in the `compute-verdict` Edge Function (TypeScript, see
-- `supabase/functions/_shared/verdict-engine.ts`); this migration just
-- creates the durable tables + the RLS policies that gate them.
--
-- Why split:
--   * `verdicts` — one row per room. The room-level decision: which
--     option won, what method produced it, what rule chip to render.
--   * `option_cuts` — many rows per verdict. One per eliminated option,
--     carrying the cut reason (machine: 'dietary', 'budget', 'walk',
--     'no_regret') and the human cut text surfaced in the S05 Cuts
--     drawer.
--
-- Naming notes:
--   * `verdicts.option_id` — references `public.options.id` (TB-05).
--     Nullable in case future no-survivor terminals want to record a
--     verdict with no winner (TB-09 will decide). For TB-06's clean-run
--     path every verdict has a winning option.
--   * `verdicts.method` — text-typed for forward compatibility with the
--     other methods enumerated in the PRD: `manual` (TB-06), `quorum`
--     (TB-07 auto-fire on full quorum), `deadline` (TB-07 timer-fired),
--     `no_survivor` (TB-09 terminal). TB-06 only writes `manual`.
--   * `verdicts.rule_text` — the rule-chip copy generated by the
--     engine. Aggregate attribution; never names a person.
--   * `option_cuts.cut_reason` — short machine token. TB-06 emits one
--     of: `dietary`, `budget`, `walk`, `no_regret`. Constrained at the
--     application layer (engine validates before insert); not enum at
--     the DB layer so the engine can evolve cut reasons without a
--     schema change.
--   * `option_cuts.cut_text` — human-readable cut text. Aggregate
--     attribution; anonymized for private constraints (allergies).
--
-- RLS shape:
--   * `verdicts` SELECT — members of the room can read the verdict.
--     Same `room_id IN (SELECT room_id FROM public.members ...)` shape
--     as `votes`.
--   * `verdicts` INSERT/UPDATE/DELETE — none. The engine writes via the
--     service-role key (bypasses RLS). Clients never write verdicts.
--   * `option_cuts` SELECT — members of the room can read cuts (join
--     through `verdicts.room_id`).
--   * `option_cuts` INSERT/UPDATE/DELETE — none. Service-role only.
--
-- Trigger plumbing for auto-fire (`AFTER INSERT ON votes`) lands in
-- TB-07; TB-06 only wires the manual-fire path via the Edge Function.

-- ── verdicts ─────────────────────────────────────────────────────────
create table if not exists public.verdicts (
    id          uuid        primary key default gen_random_uuid(),
    room_id     uuid        not null references public.rooms (id) on delete cascade,
    option_id   uuid        references public.options (id),
    computed_at timestamptz not null default now(),
    method      text        not null
        check (method in ('manual', 'quorum', 'deadline', 'no_survivor')),
    rule_text   text        not null,
    -- One verdict per room. The trigger-fire path (TB-07) will use an
    -- ON CONFLICT clause to swallow duplicate compute calls. Manual
    -- `compute-verdict` invocations during TB-06 manual testing should
    -- be against a fresh room each time.
    unique (room_id)
);

comment on table public.verdicts is
    'One row per room. The VerdictEngine''s server-authoritative output: which option won, what rule produced it, when it was computed. iOS reads this row to render S05; iOS never recomputes a verdict.';

comment on column public.verdicts.method is
    'How the verdict was triggered. TB-06 only writes manual; TB-07 adds quorum + deadline; TB-09 adds no_survivor.';

comment on column public.verdicts.rule_text is
    'The rule-chip copy. Aggregate attribution; never names a person. Per verdict-screen-spec §"Name the rule, not the picker".';

create index if not exists verdicts_room_id_idx on public.verdicts (room_id);

-- ── option_cuts ──────────────────────────────────────────────────────
create table if not exists public.option_cuts (
    verdict_id uuid not null references public.verdicts (id) on delete cascade,
    option_id  uuid not null references public.options (id) on delete cascade,
    cut_reason text not null,
    cut_text   text not null,
    primary key (verdict_id, option_id)
);

comment on table public.option_cuts is
    'Eliminated options per verdict — feeds the S05 Cuts drawer. cut_reason is a short machine token (dietary, budget, walk, no_regret); cut_text is the human label.';

create index if not exists option_cuts_verdict_id_idx on public.option_cuts (verdict_id);

-- ── RLS ──────────────────────────────────────────────────────────────
alter table public.verdicts enable row level security;
alter table public.option_cuts enable row level security;

-- Members of the room read the verdict.
drop policy if exists "verdicts_select_room_members" on public.verdicts;
create policy "verdicts_select_room_members" on public.verdicts
    for select
    to authenticated
    using (
        room_id in (select room_id from public.members where user_id = (select auth.uid()))
    );

-- Members of the room read the cuts (join through the verdict).
drop policy if exists "option_cuts_select_room_members" on public.option_cuts;
create policy "option_cuts_select_room_members" on public.option_cuts
    for select
    to authenticated
    using (
        verdict_id in (
            select v.id from public.verdicts v
            where v.room_id in (
                select m.room_id from public.members m where m.user_id = (select auth.uid())
            )
        )
    );

-- No INSERT / UPDATE / DELETE policies — RLS denies by default. The
-- VerdictEngine writes via the service-role key (RLS bypass), which is
-- the only mutation path. Manual seeding for tests uses the same path.

-- Now that `members` exists (TB-02) we can backfill the
-- `options: room members read` SELECT policy that TB-05 left out
-- (see comments in 20260513183000_places_and_options.sql). The S05
-- verdict surface reads `options.name` via a join when rendering the
-- cuts drawer, so iOS members need SELECT access to their rooms'
-- options. Edge Functions still use the service-role key for writes.
drop policy if exists "options_select_room_members" on public.options;
create policy "options_select_room_members" on public.options
    for select
    to authenticated
    using (
        room_id in (select room_id from public.members where user_id = (select auth.uid()))
    );
